name: Commit validation pipeline

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  type-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PHPStan
        run: docker run --rm --quiet --volume .:/source --workdir /source --tty r1n0x/string-language-container:1.0.1 composer run-script phpstan-github

  style-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    needs: type-check

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CS-Fixer
        run: docker run --rm --quiet --volume .:/source --workdir /source --tty r1n0x/string-language-container:1.0.1 composer run-script csfixer-github

  tests-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    needs: style-check

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PHPUnit
        run: docker run --rm --quiet --volume .:/source --workdir /source --tty r1n0x/string-language-container:1.0.1 composer run-script phpunit-github

      - name: Upload PHPUnit generated coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: github.event_name == 'push'